name: libvmaf
on:
  push:
    #paths:
    #- 'libvmaf/**'
    #- '.github/**'
  pull_request:
    #paths:
    #- 'libvmaf/**'
    #- '.github/**'

env:
  DEBIAN_FRONTEND: noninteractive
  LD_LIBRARY_PATH: /usr/local/lib/x86_64-linux-gnu

jobs:
  ffmpeg:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            CC: ccache gcc
            CXX: ccache g++
          - os: macos-10.15
            CC: ccache clang
            CXX: ccache clang++
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    steps:
      - name: Install dependencies (ubuntu)
        if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo apt-get update
          sudo -E apt-get -yq install ccache gcc yasm
      - name: Install dependencies (mac)
        if: matrix.os == 'macos-10.15'
        run: |
          brew update
          brew install ccache nasm pkg-config
      - uses: actions/checkout@v2
      - name: Prepare FFmpeg
        env:
          CFLAGS: -static
        run: |
          git clone -q --branch master --depth=1 "https://github.com/FFmpeg/FFmpeg" ffmpeg
          [ -d "$HOME/.ccache" ] && sudo chown -R runner: "$HOME/.ccache"
          cd ffmpeg
          ./configure --enable-version3 --enable-pic --cc="$CC" --cxx="$CXX" || { less ffbuild/config.log; exit 1; }
      - name: Cat config.asm
        run: cat ffmpeg/config.asm
      - name: Make FFmpeg
        run: |
          sudo make -C ffmpeg -j $(getconf _NPROCESSORS_ONLN 2>/dev/null || sysctl -n hw.ncpu) V=1 install
